# Generated by Django 5.0 on 2023-12-26 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=15)),
                ('publisher', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('createdAt', models.TimeField(auto_now_add=True)),
                ('updatedAt', models.TimeField(auto_now=True)),
                ('bookshelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookshelf')),
            ],
        ),
    ]
